# Generated by Django 4.0.3 on 2022-03-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_members_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srNo', models.IntegerField()),
                ('companyName', models.CharField(max_length=50)),
                ('jobTitle', models.CharField(max_length=100)),
                ('jobLocation', models.CharField(max_length=100)),
            ],
        ),
    ]
